//! UniFFI bindings over the credSync core's event/effect surface.
//!
//! The boundary is deliberately small and message-shaped — feed an event in, drain effects out.
//! No object graph crosses it. That keeps every binding thin and keeps React Native's Hermes
//! engine, which is single-threaded, happy.
//!
//! # Unsafe
//!
//! This is the one crate permitted to contain `unsafe`, and only in scaffolding generated by
//! UniFFI. Hand-written `unsafe` is a review-blocking defect. [`credsync_core`] and
//! [`credsync_protocol`] remain `#![forbid(unsafe_code)]`.
//!
//! # Status
//!
//! Scaffolded at CS-1. The UniFFI surface arrives at CS-23, storage adapters at CS-24 and CS-26.
//!
//! [`credsync_core`]: https://github.com/TheAfricanDreamLab/credsync/tree/main/credsync-core
//! [`credsync_protocol`]: https://github.com/TheAfricanDreamLab/credsync/tree/main/credsync-protocol

#![deny(unsafe_op_in_unsafe_fn)]
